# -*- coding: utf-8 -*-
"""src/reconciliation/llm_classifier

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wet7eEoLp9wBDx0MK3Sso4sP9ya1xsrO
"""

from groq import Groq

client = Groq(api_key="YOUR_API_KEY")

def classify_transactions(invoice_text: str):

    prompt = f"""
    Extract the following from the invoice:
    - Vendor
    - Amount
    - Date
    - Category

    Return as JSON.
    Invoice:
    {invoice_text}
    """

    response = client.chat.completions.create(
        model="llama3-70b",
        messages=[{"role": "user", "content": prompt}]
    )

    return response.choices[0].message["content"]