# -*- coding: utf-8 -*-
"""src/utils/config

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wet7eEoLp9wBDx0MK3Sso4sP9ya1xsrO
"""

import os
from dotenv import load_dotenv

load_dotenv()

GROQ_API_KEY = os.getenv("GROQ_API_KEY")