# -*- coding: utf-8 -*-
"""src/reconciliation/anomaly_detector

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wet7eEoLp9wBDx0MK3Sso4sP9ya1xsrO
"""

def detect_anomalies(results):
    anomalies = []

    for m in results["matches"]:
        if m["score"] < 90:
            anomalies.append({
                "type": "low_confidence",
                "details": m
            })

    if len(results["unmatched"]) > 0:
        anomalies.append({
            "type": "unmatched_transactions",
            "count": len(results["unmatched"])
        })

    return anomalies