# -*- coding: utf-8 -*-
"""src/ingestion/csv_loaderr

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wet7eEoLp9wBDx0MK3Sso4sP9ya1xsrO
"""

import pandas as pd

def load_bank_csv(path: str):
    return pd.read_csv(path)