# -*- coding: utf-8 -*-
"""src/reconciliation/matcher

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wet7eEoLp9wBDx0MK3Sso4sP9ya1xsrO
"""

from fuzzywuzzy import fuzz

def reconcile(invoice, bank_df):

    matches = []
    unmatched = []

    for _, row in bank_df.iterrows():
        score = fuzz.partial_ratio(str(invoice["amount"]), str(row["Amount"]))

        if score > 80:
            matches.append({"invoice": invoice, "bank": row.to_dict(), "score": score})
        else:
            unmatched.append(row.to_dict())

    return {"matches": matches, "unmatched": unmatched}