# -*- coding: utf-8 -*-
"""src/ingestion/pdf_loader

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wet7eEoLp9wBDx0MK3Sso4sP9ya1xsrO
"""

import pytesseract
from pdf2image import convert_from_path

def extract_pdf_text(path: str):
    pages = convert_from_path(path)
    full_text = ""

    for page in pages:
        text = pytesseract.image_to_string(page)
        full_text += text + "\n"

    return full_text