# -*- coding: utf-8 -*-
"""src/api/routes.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wet7eEoLp9wBDx0MK3Sso4sP9ya1xsrO
"""

from fastapi import APIRouter
from src.ingestion.pdf_loader import extract_pdf_text
from src.ingestion.csv_loader import load_bank_csv
from src.reconciliation.llm_classifier import classify_transactions
from src.reconciliation.matcher import reconcile
from src.reconciliation.anomaly_detector import detect_anomalies

router = APIRouter()

@router.post("/reconcile")
def reconcile_files(invoice_pdf: str, bank_csv: str):

    invoice_text = extract_pdf_text(invoice_pdf)
    bank_df = load_bank_csv(bank_csv)

    classified = classify_transactions(invoice_text)
    results = reconcile(classified, bank_df)
    anomalies = detect_anomalies(results)

    return {
        "status": "completed",
        "classified": classified,
        "results": results,
        "anomalies": anomalies
    }