# -*- coding: utf-8 -*-
"""src/main.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wet7eEoLp9wBDx0MK3Sso4sP9ya1xsrO
"""

from fastapi import FastAPI
from src.api.routes import router

app = FastAPI(title="AI Financial Reconciliation Engine")

app.include_router(router)

@app.get("/")
def root():
    return {"message": "AI Financial Reconciliation Engine is running"}